In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
# sentence

sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
# Define the vocalbary size

vocab_size = 10000


In [6]:
# One hot repesentation

onehot_repr = [one_hot(words, vocab_size) for words in sent]
onehot_repr

[[3991, 4523, 50, 5567],
 [3991, 4523, 50, 2267],
 [3991, 7292, 50, 2274],
 [7483, 5840, 9477, 9812, 4034],
 [7483, 5840, 9477, 9812, 24],
 [2381, 3991, 1153, 50, 2488],
 [736, 5282, 7532, 9812]]

In [8]:
# word embedding repesentation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np


In [9]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)

In [11]:
embedded_docs

array([[   0,    0,    0,    0, 3991, 4523,   50, 5567],
       [   0,    0,    0,    0, 3991, 4523,   50, 2267],
       [   0,    0,    0,    0, 3991, 7292,   50, 2274],
       [   0,    0,    0, 7483, 5840, 9477, 9812, 4034],
       [   0,    0,    0, 7483, 5840, 9477, 9812,   24],
       [   0,    0,    0, 2381, 3991, 1153,   50, 2488],
       [   0,    0,    0,    0,  736, 5282, 7532, 9812]], dtype=int32)

In [12]:
# feature representation

dim = 10

In [13]:
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

D:\Projects\DEEP LEARNING NLP\.venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [17]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step


array([[[ 6.70794398e-03, -1.84519067e-02,  3.34336273e-02,
         -1.62026286e-02, -8.80478695e-03,  3.10771354e-02,
         -1.76547542e-02,  1.55410878e-02, -2.27329861e-02,
         -4.42505591e-02],
        [ 6.70794398e-03, -1.84519067e-02,  3.34336273e-02,
         -1.62026286e-02, -8.80478695e-03,  3.10771354e-02,
         -1.76547542e-02,  1.55410878e-02, -2.27329861e-02,
         -4.42505591e-02],
        [ 6.70794398e-03, -1.84519067e-02,  3.34336273e-02,
         -1.62026286e-02, -8.80478695e-03,  3.10771354e-02,
         -1.76547542e-02,  1.55410878e-02, -2.27329861e-02,
         -4.42505591e-02],
        [ 6.70794398e-03, -1.84519067e-02,  3.34336273e-02,
         -1.62026286e-02, -8.80478695e-03,  3.10771354e-02,
         -1.76547542e-02,  1.55410878e-02, -2.27329861e-02,
         -4.42505591e-02],
        [ 2.99439691e-02, -1.33155100e-02, -2.43484974e-04,
         -8.09903070e-03, -3.14195901e-02, -1.13206394e-02,
          1.74104236e-02, -1.06264353e-02,  3.312844

In [25]:
embedded_docs[0]

array([   0,    0,    0,    0, 3991, 4523,   50, 5567], dtype=int32)

In [26]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step


array([[[ 0.00670794, -0.01845191,  0.03343363, -0.01620263,
         -0.00880479,  0.03107714, -0.01765475,  0.01554109,
         -0.02273299, -0.04425056],
        [ 0.00670794, -0.01845191,  0.03343363, -0.01620263,
         -0.00880479,  0.03107714, -0.01765475,  0.01554109,
         -0.02273299, -0.04425056],
        [ 0.00670794, -0.01845191,  0.03343363, -0.01620263,
         -0.00880479,  0.03107714, -0.01765475,  0.01554109,
         -0.02273299, -0.04425056],
        [ 0.00670794, -0.01845191,  0.03343363, -0.01620263,
         -0.00880479,  0.03107714, -0.01765475,  0.01554109,
         -0.02273299, -0.04425056],
        [ 0.02994397, -0.01331551, -0.00024348, -0.00809903,
         -0.03141959, -0.01132064,  0.01741042, -0.01062644,
          0.03312844, -0.04725197],
        [ 0.02408559,  0.04421588,  0.04542169,  0.03115845,
         -0.00265442,  0.04981649, -0.03014678,  0.03787733,
          0.00497583,  0.00635814],
        [ 0.04313756,  0.04613084, -0.00231767,  0.0